name: Docker Image CI

on: workflow_dispatch
  # push:
  #   branches: [ "vite_ssr" ]
  # pull_request:
  #   branches: [ "vite_ssr" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # pull代码到运行服务器上
    - name: image tag
      run:  echo "SHORT_SHA=`echo ${{github.sha}} | cut -c1-8`" >> $GITHUB_ENV
    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{env.SHORT_SHA}} # 用于标记容器版本号
        ALIYUN_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        ALIYUN_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        docker login --username=$ALIYUN_USERNAME --password=$ALIYUN_PASSWORD registry.cn-hangzhou.aliyuncs.com
        docker build -t registry.cn-hangzhou.aliyuncs.com/yonghaoy/aoeba_qd:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/yonghaoy/aoeba_qd:$IMAGE_TAG
        echo "镜像地址：registry.cn-hangzhou.aliyuncs.com/yonghaoy/aoeba_qd:`$IMAGE_TAG`"
